--------------------------------------------------------
-- Archivo creado  - viernes-mayo-27-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence EXAMEN_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."EXAMEN_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GRUPO_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."GRUPO_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HORARIOO_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."HORARIOO_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OPCION_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."OPCION_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PLAN_ESTUDIO_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."PLAN_ESTUDIO_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PREGUNTA_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."PREGUNTA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRIVACIDAD_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."PRIVACIDAD_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RESPUESTA_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."RESPUESTA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RESPUESTAS_IDRESPUESTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."RESPUESTAS_IDRESPUESTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROL_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."ROL_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TEMA_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."TEMA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TIPO_PREGUNTA_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBA"."TIPO_PREGUNTA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ASIGNATURA
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."ASIGNATURA" 
   (	"IDASIGNATURA" NUMBER(*,0), 
	"PLAN_ESTUDIO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BANCO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."BANCO" 
   (	"EXAMEN_ID" NUMBER(*,0), 
	"PREGUNTA_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOCENTE
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."DOCENTE" 
   (	"PERSONA_IDENTIFICACION" NUMBER(*,0), 
	"SUELDO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTE
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."ESTUDIANTE" 
   (	"PERSONA_IDENTIFICACION" NUMBER(*,0), 
	"SEMESTREACTUAL" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTE_EXAMEN
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."ESTUDIANTE_EXAMEN" 
   (	"ESTUDIANTE_IDENTIFICACION" NUMBER(*,0), 
	"EXAMENEST_ID" NUMBER(*,0), 
	"CALIFICACION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTE_EXAMEN_BANCO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."ESTUDIANTE_EXAMEN_BANCO" 
   (	"EXAMENEST_ID" NUMBER(*,0), 
	"ESTEXA_ESTUDIANTE_ID" NUMBER(*,0), 
	"BANCO_EXAMEN_ID" NUMBER(*,0), 
	"BANCO_PREGUNTA_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTE_GRUPO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."ESTUDIANTE_GRUPO" 
   (	"ESTUDIANTE_IDENTIFICACION" NUMBER(*,0), 
	"GRUPO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXAMEN
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."EXAMEN" 
   (	"ID" NUMBER(*,0), 
	"DOCENTE_PERSONA_IDENTIFICACION" NUMBER(*,0), 
	"FECHA_INCIO" VARCHAR2(11 BYTE), 
	"FECHA_FIN" VARCHAR2(11 BYTE), 
	"NUMERO_PREGUNTAS" NUMBER(*,0), 
	"TIEMPO_MINUTOS" NUMBER, 
	"PESOPORCETAJE" FLOAT(126), 
	"UMBRAL" FLOAT(126), 
	"ID_TEMA" NUMBER, 
	"ID_GRUPO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GRUPO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."GRUPO" 
   (	"ID" NUMBER(*,0), 
	"DOCENTE_PERSONA_IDENTIFICACION" NUMBER(*,0), 
	"ASIGNATURA_IDASIGNATURA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HORARIOO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."HORARIOO" 
   (	"ID" NUMBER(*,0), 
	"HORA_INI" DATE, 
	"HORA_FIN" DATE, 
	"NUMERO_SALON" VARCHAR2(50 BYTE), 
	"GRUPO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OPCION
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."OPCION" 
   (	"ID" NUMBER(*,0), 
	"OPCION" VARCHAR2(120 BYTE), 
	"PREGUNTA_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."PERSONA" 
   (	"IDENTIFICACION" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(240 BYTE), 
	"APELLIDO_MATERNO" VARCHAR2(120 BYTE), 
	"APELLIDO_PATERNO" VARCHAR2(120 BYTE), 
	"EMAIL" VARCHAR2(240 BYTE), 
	"CLAVE" VARCHAR2(50 BYTE), 
	"ROL_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLAN_ESTUDIO
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."PLAN_ESTUDIO" 
   (	"ID" NUMBER(*,0), 
	"UNIDADES" NUMBER(*,0), 
	"CONTENIDO" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREGUNTA
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."PREGUNTA" 
   (	"ID" NUMBER(*,0), 
	"ENUNCIADO" VARCHAR2(240 BYTE), 
	"TIPO_PREGUNTA_ID" NUMBER(*,0), 
	"PRIVACIDAD_ID" NUMBER(*,0), 
	"TEMA_ID" NUMBER(*,0), 
	"DOCENTE_PERSONA_IDENTIFICACION" NUMBER(*,0), 
	"PREGUNTA_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRIVACIDAD
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."PRIVACIDAD" 
   (	"ID" NUMBER(*,0), 
	"TIPO" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESPUESTA
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."RESPUESTA" 
   (	"ID" NUMBER(*,0), 
	"RESPUESTA" VARCHAR2(240 BYTE), 
	"PREGUNTA_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAS
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."RESPUESTAS" 
   (	"IDRESPUESTA" NUMBER(*,0), 
	"OPCION_ID" NUMBER(*,0), 
	"ESTEXBAN_EXAMENEST_ID" NUMBER(*,0), 
	"ESTEXBAN_ESTEXA_ESTUDIANTE_ID" NUMBER(*,0), 
	"ESTEXBAN_BANCO_EXAMEN_ID" NUMBER(*,0), 
	"ESTEXBAN_BANCO_PREGUNTA_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."ROL" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEMA
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."TEMA" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(120 BYTE), 
	"PLAN_ESTUDIO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_PREGUNTA
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."TIPO_PREGUNTA" 
   (	"ID" NUMBER(*,0), 
	"TIPO" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PRUEBA.ASIGNATURA
SET DEFINE OFF;
Insert into PRUEBA.ASIGNATURA (IDASIGNATURA,PLAN_ESTUDIO_ID) values ('1','1');
REM INSERTING into PRUEBA.BANCO
SET DEFINE OFF;
REM INSERTING into PRUEBA.DOCENTE
SET DEFINE OFF;
Insert into PRUEBA.DOCENTE (PERSONA_IDENTIFICACION,SUELDO) values ('1005094694','500000');
REM INSERTING into PRUEBA.ESTUDIANTE
SET DEFINE OFF;
REM INSERTING into PRUEBA.ESTUDIANTE_EXAMEN
SET DEFINE OFF;
REM INSERTING into PRUEBA.ESTUDIANTE_EXAMEN_BANCO
SET DEFINE OFF;
REM INSERTING into PRUEBA.ESTUDIANTE_GRUPO
SET DEFINE OFF;
REM INSERTING into PRUEBA.EXAMEN
SET DEFINE OFF;
Insert into PRUEBA.EXAMEN (ID,DOCENTE_PERSONA_IDENTIFICACION,FECHA_INCIO,FECHA_FIN,NUMERO_PREGUNTAS,TIEMPO_MINUTOS,PESOPORCETAJE,UMBRAL,ID_TEMA,ID_GRUPO) values ('10','1005094694','2022-05-27','2022-05-28','5','5','1','3','1',null);
REM INSERTING into PRUEBA.GRUPO
SET DEFINE OFF;
Insert into PRUEBA.GRUPO (ID,DOCENTE_PERSONA_IDENTIFICACION,ASIGNATURA_IDASIGNATURA,NOMBRE) values ('5','1005094694','1','Programacion 1');
REM INSERTING into PRUEBA.HORARIOO
SET DEFINE OFF;
REM INSERTING into PRUEBA.OPCION
SET DEFINE OFF;
REM INSERTING into PRUEBA.PERSONA
SET DEFINE OFF;
Insert into PRUEBA.PERSONA (IDENTIFICACION,NOMBRE,APELLIDO_MATERNO,APELLIDO_PATERNO,EMAIL,CLAVE,ROL_ID) values ('1005094694','Santiago','Arias','Garcia','santiarias@gmail.com','SANTInacional','1');
REM INSERTING into PRUEBA.PLAN_ESTUDIO
SET DEFINE OFF;
Insert into PRUEBA.PLAN_ESTUDIO (ID,UNIDADES,CONTENIDO) values ('1','4','full java');
REM INSERTING into PRUEBA.PREGUNTA
SET DEFINE OFF;
REM INSERTING into PRUEBA.PRIVACIDAD
SET DEFINE OFF;
Insert into PRUEBA.PRIVACIDAD (ID,TIPO) values ('1','publico');
REM INSERTING into PRUEBA.RESPUESTA
SET DEFINE OFF;
REM INSERTING into PRUEBA.RESPUESTAS
SET DEFINE OFF;
REM INSERTING into PRUEBA.ROL
SET DEFINE OFF;
Insert into PRUEBA.ROL (ID,NOMBRE) values ('1','Profesor');
REM INSERTING into PRUEBA.TEMA
SET DEFINE OFF;
Insert into PRUEBA.TEMA (ID,NOMBRE,PLAN_ESTUDIO_ID) values ('1','Programacion','1');
REM INSERTING into PRUEBA.TIPO_PREGUNTA
SET DEFINE OFF;
Insert into PRUEBA.TIPO_PREGUNTA (ID,TIPO) values ('1','opcion multiple unica respuesta');
--------------------------------------------------------
--  DDL for Index BANCO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."BANCO_PK" ON "PRUEBA"."BANCO" ("EXAMEN_ID", "PREGUNTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HORARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."HORARIO_PK" ON "PRUEBA"."HORARIOO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GRUPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."GRUPO_PK" ON "PRUEBA"."GRUPO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLAN_ESTUDIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."PLAN_ESTUDIO_PK" ON "PRUEBA"."PLAN_ESTUDIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."PERSONA_PK" ON "PRUEBA"."PERSONA" ("IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROFESOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."PROFESOR_PK" ON "PRUEBA"."DOCENTE" ("PERSONA_IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESPUESTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."RESPUESTAS_PK" ON "PRUEBA"."RESPUESTAS" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OPCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."OPCION_PK" ON "PRUEBA"."OPCION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESPUESTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."RESPUESTA_PK" ON "PRUEBA"."RESPUESTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSONA__UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."PERSONA__UN" ON "PRUEBA"."PERSONA" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXAMEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."EXAMEN_PK" ON "PRUEBA"."EXAMEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PREGUNTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."PREGUNTA_PK" ON "PRUEBA"."PREGUNTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTUDIANTE_EXAMEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ESTUDIANTE_EXAMEN_PK" ON "PRUEBA"."ESTUDIANTE_EXAMEN" ("EXAMENEST_ID", "ESTUDIANTE_IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTUDIANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ESTUDIANTE_PK" ON "PRUEBA"."ESTUDIANTE" ("PERSONA_IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ASIGNATURA__UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ASIGNATURA__UN" ON "PRUEBA"."ASIGNATURA" ("PLAN_ESTUDIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ROL_PK" ON "PRUEBA"."ROL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."TEMA_PK" ON "PRUEBA"."TEMA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ASIGNATURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ASIGNATURA_PK" ON "PRUEBA"."ASIGNATURA" ("IDASIGNATURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTUDIANTE_EXAMEN_BANCO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ESTUDIANTE_EXAMEN_BANCO_PK" ON "PRUEBA"."ESTUDIANTE_EXAMEN_BANCO" ("EXAMENEST_ID", "ESTEXA_ESTUDIANTE_ID", "BANCO_EXAMEN_ID", "BANCO_PREGUNTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPO_PREGUNTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."TIPO_PREGUNTA_PK" ON "PRUEBA"."TIPO_PREGUNTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIVACIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."PRIVACIDAD_PK" ON "PRUEBA"."PRIVACIDAD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTUDIANTE_GRUPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."ESTUDIANTE_GRUPO_PK" ON "PRUEBA"."ESTUDIANTE_GRUPO" ("ESTUDIANTE_IDENTIFICACION", "GRUPO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger EXAMEN_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."EXAMEN_ID_TRG" 
BEFORE INSERT ON Examen 
FOR EACH ROW 
 WHEN (NEW.id IS NULL) BEGIN
:new.id := examen_id_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."EXAMEN_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger GRUPO_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."GRUPO_ID_TRG" 
BEFORE INSERT ON Grupo 
FOR EACH ROW 
 WHEN (NEW.id IS NULL) BEGIN
:new.id := grupo_id_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."GRUPO_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HORARIOO_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."HORARIOO_ID_TRG" 
BEFORE INSERT ON Horarioo 
FOR EACH ROW 
 WHEN (NEW.id IS NULL) BEGIN
:new.id := horarioo_id_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."HORARIOO_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OPCION_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."OPCION_ID_TRG" 
BEFORE INSERT ON Opcion 
FOR EACH ROW 
 WHEN (NEW.id IS NULL) BEGIN
:new.id := opcion_id_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."OPCION_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PLAN_ESTUDIO_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."PLAN_ESTUDIO_ID_TRG" 
BEFORE INSERT ON Plan_estudio 
FOR EACH ROW 
 WHEN (NEW.id IS NULL) BEGIN
:new.id := plan_estudio_id_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."PLAN_ESTUDIO_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PREGUNTA_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."PREGUNTA_ID_TRG" 
BEFORE INSERT ON Pregunta 
FOR EACH ROW 
 WHEN (NEW.id IS NULL) BEGIN
:new.id := pregunta_id_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."PREGUNTA_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRIVACIDAD_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."PRIVACIDAD_ID_TRG" 
BEFORE INSERT ON Privacidad 
FOR EACH ROW 
 WHEN (NEW.id IS NULL) BEGIN
:new.id := privacidad_id_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."PRIVACIDAD_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RESPUESTA_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."RESPUESTA_ID_TRG" 
BEFORE INSERT ON Respuesta 
FOR EACH ROW 
 WHEN (NEW.id IS NULL) BEGIN
:new.id := respuesta_id_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."RESPUESTA_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RESPUESTAS_IDRESPUESTA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."RESPUESTAS_IDRESPUESTA_TRG" 
BEFORE INSERT ON Respuestas 
FOR EACH ROW 
 WHEN (NEW.idRespuesta IS NULL) BEGIN
:new.idrespuesta := respuestas_idrespuesta_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."RESPUESTAS_IDRESPUESTA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROL_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."ROL_ID_TRG" 
BEFORE INSERT ON Rol 
FOR EACH ROW 
 WHEN (NEW.id IS NULL) BEGIN
:new.id := rol_id_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."ROL_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TEMA_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."TEMA_ID_TRG" 
BEFORE INSERT ON Tema 
FOR EACH ROW 
 WHEN (NEW.id IS NULL) BEGIN
:new.id := tema_id_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."TEMA_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TIPO_PREGUNTA_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRUEBA"."TIPO_PREGUNTA_ID_TRG" 
BEFORE INSERT ON Tipo_Pregunta 
FOR EACH ROW 
 WHEN (NEW.id IS NULL) BEGIN
:new.id := tipo_pregunta_id_seq.nextval;

end;

/
ALTER TRIGGER "PRUEBA"."TIPO_PREGUNTA_ID_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table EXAMEN
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."EXAMEN" ADD CONSTRAINT "EXAMEN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."EXAMEN" MODIFY ("UMBRAL" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EXAMEN" MODIFY ("PESOPORCETAJE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EXAMEN" MODIFY ("TIEMPO_MINUTOS" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EXAMEN" MODIFY ("NUMERO_PREGUNTAS" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EXAMEN" MODIFY ("FECHA_FIN" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EXAMEN" MODIFY ("FECHA_INCIO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EXAMEN" MODIFY ("DOCENTE_PERSONA_IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."EXAMEN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEMA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."TEMA" ADD CONSTRAINT "TEMA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."TEMA" MODIFY ("PLAN_ESTUDIO_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."TEMA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."TEMA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."PERSONA" ADD CONSTRAINT "PERSONA__UN" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."PERSONA" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY ("IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."PERSONA" MODIFY ("ROL_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PERSONA" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PERSONA" MODIFY ("EMAIL" CONSTRAINT "NNC_PERSONA_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PERSONA" MODIFY ("APELLIDO_PATERNO" CONSTRAINT "NNC_PERSONA_APELLIDO_PATERNO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PERSONA" MODIFY ("APELLIDO_MATERNO" CONSTRAINT "NNC_PERSONA_APELLIDO_MATERNO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PERSONA" MODIFY ("NOMBRE" CONSTRAINT "NNC_PERSONA_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PERSONA" MODIFY ("IDENTIFICACION" CONSTRAINT "NNC_PERSONA_PERSONA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAN_ESTUDIO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."PLAN_ESTUDIO" ADD CONSTRAINT "PLAN_ESTUDIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."PLAN_ESTUDIO" MODIFY ("CONTENIDO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PLAN_ESTUDIO" MODIFY ("UNIDADES" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PLAN_ESTUDIO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTUDIANTE_GRUPO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ESTUDIANTE_GRUPO" ADD CONSTRAINT "ESTUDIANTE_GRUPO_PK" PRIMARY KEY ("ESTUDIANTE_IDENTIFICACION", "GRUPO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."ESTUDIANTE_GRUPO" MODIFY ("GRUPO_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ESTUDIANTE_GRUPO" MODIFY ("ESTUDIANTE_IDENTIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_PK" PRIMARY KEY ("PERSONA_IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."ESTUDIANTE" MODIFY ("PERSONA_IDENTIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASIGNATURA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ASIGNATURA" ADD CONSTRAINT "ASIGNATURA__UN" UNIQUE ("PLAN_ESTUDIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."ASIGNATURA" ADD CONSTRAINT "ASIGNATURA_PK" PRIMARY KEY ("IDASIGNATURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."ASIGNATURA" MODIFY ("PLAN_ESTUDIO_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ASIGNATURA" MODIFY ("IDASIGNATURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANCO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."BANCO" ADD CONSTRAINT "BANCO_PK" PRIMARY KEY ("EXAMEN_ID", "PREGUNTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."BANCO" MODIFY ("PREGUNTA_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."BANCO" MODIFY ("EXAMEN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OPCION
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."OPCION" ADD CONSTRAINT "OPCION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."OPCION" MODIFY ("PREGUNTA_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."OPCION" MODIFY ("OPCION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."OPCION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."PREGUNTA" ADD CONSTRAINT "PREGUNTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."PREGUNTA" MODIFY ("DOCENTE_PERSONA_IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PREGUNTA" MODIFY ("TEMA_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PREGUNTA" MODIFY ("PRIVACIDAD_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PREGUNTA" MODIFY ("TIPO_PREGUNTA_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PREGUNTA" MODIFY ("ENUNCIADO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PREGUNTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."RESPUESTA" ADD CONSTRAINT "RESPUESTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."RESPUESTA" MODIFY ("PREGUNTA_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."RESPUESTA" MODIFY ("RESPUESTA" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."RESPUESTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ROL" ADD CONSTRAINT "ROL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."ROL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ROL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTUDIANTE_EXAMEN_BANCO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN_BANCO" ADD CONSTRAINT "ESTUDIANTE_EXAMEN_BANCO_PK" PRIMARY KEY ("EXAMENEST_ID", "ESTEXA_ESTUDIANTE_ID", "BANCO_EXAMEN_ID", "BANCO_PREGUNTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN_BANCO" MODIFY ("BANCO_PREGUNTA_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN_BANCO" MODIFY ("BANCO_EXAMEN_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN_BANCO" MODIFY ("ESTEXA_ESTUDIANTE_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN_BANCO" MODIFY ("EXAMENEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTUDIANTE_EXAMEN
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN" ADD CONSTRAINT "ESTUDIANTE_EXAMEN_PK" PRIMARY KEY ("EXAMENEST_ID", "ESTUDIANTE_IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN" MODIFY ("CALIFICACION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN" MODIFY ("EXAMENEST_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN" MODIFY ("ESTUDIANTE_IDENTIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRUPO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."GRUPO" ADD CONSTRAINT "GRUPO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."GRUPO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."GRUPO" MODIFY ("ASIGNATURA_IDASIGNATURA" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."GRUPO" MODIFY ("DOCENTE_PERSONA_IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."GRUPO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_PREGUNTA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."TIPO_PREGUNTA" ADD CONSTRAINT "TIPO_PREGUNTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."TIPO_PREGUNTA" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."TIPO_PREGUNTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAS
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."RESPUESTAS" ADD CONSTRAINT "RESPUESTAS_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."RESPUESTAS" MODIFY ("ESTEXBAN_BANCO_PREGUNTA_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."RESPUESTAS" MODIFY ("ESTEXBAN_BANCO_EXAMEN_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."RESPUESTAS" MODIFY ("ESTEXBAN_ESTEXA_ESTUDIANTE_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."RESPUESTAS" MODIFY ("ESTEXBAN_EXAMENEST_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."RESPUESTAS" MODIFY ("OPCION_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."RESPUESTAS" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HORARIOO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."HORARIOO" ADD CONSTRAINT "HORARIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."HORARIOO" MODIFY ("GRUPO_ID" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."HORARIOO" MODIFY ("NUMERO_SALON" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."HORARIOO" MODIFY ("HORA_FIN" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."HORARIOO" MODIFY ("HORA_INI" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."HORARIOO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCENTE
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."DOCENTE" ADD CONSTRAINT "PROFESOR_PK" PRIMARY KEY ("PERSONA_IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."DOCENTE" MODIFY ("PERSONA_IDENTIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRIVACIDAD
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."PRIVACIDAD" ADD CONSTRAINT "PRIVACIDAD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRUEBA"."PRIVACIDAD" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBA"."PRIVACIDAD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ASIGNATURA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ASIGNATURA" ADD CONSTRAINT "ASIGNATURA_PLAN_ESTUDIO_FK" FOREIGN KEY ("PLAN_ESTUDIO_ID")
	  REFERENCES "PRUEBA"."PLAN_ESTUDIO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BANCO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."BANCO" ADD CONSTRAINT "BANCO_EXAMEN_FK" FOREIGN KEY ("EXAMEN_ID")
	  REFERENCES "PRUEBA"."EXAMEN" ("ID") ENABLE;
  ALTER TABLE "PRUEBA"."BANCO" ADD CONSTRAINT "BANCO_PREGUNTA_FK" FOREIGN KEY ("PREGUNTA_ID")
	  REFERENCES "PRUEBA"."PREGUNTA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCENTE
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."DOCENTE" ADD CONSTRAINT "PROFESOR_PERSONA_FK" FOREIGN KEY ("PERSONA_IDENTIFICACION")
	  REFERENCES "PRUEBA"."PERSONA" ("IDENTIFICACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_PERSONA_FK" FOREIGN KEY ("PERSONA_IDENTIFICACION")
	  REFERENCES "PRUEBA"."PERSONA" ("IDENTIFICACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTE_EXAMEN
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN" ADD CONSTRAINT "ESTUDIANTE_EXAMEN_EXAMEN_FK" FOREIGN KEY ("EXAMENEST_ID")
	  REFERENCES "PRUEBA"."EXAMEN" ("ID") ENABLE;
  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN" ADD CONSTRAINT "EXAMEN_ESTUDIANTE_FK" FOREIGN KEY ("ESTUDIANTE_IDENTIFICACION")
	  REFERENCES "PRUEBA"."ESTUDIANTE" ("PERSONA_IDENTIFICACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTE_EXAMEN_BANCO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN_BANCO" ADD CONSTRAINT "ESTEXBAN_BANCO_FK" FOREIGN KEY ("BANCO_EXAMEN_ID", "BANCO_PREGUNTA_ID")
	  REFERENCES "PRUEBA"."BANCO" ("EXAMEN_ID", "PREGUNTA_ID") ENABLE;
  ALTER TABLE "PRUEBA"."ESTUDIANTE_EXAMEN_BANCO" ADD CONSTRAINT "ESTEXBAN_EXAMEN_FK" FOREIGN KEY ("EXAMENEST_ID", "ESTEXA_ESTUDIANTE_ID")
	  REFERENCES "PRUEBA"."ESTUDIANTE_EXAMEN" ("EXAMENEST_ID", "ESTUDIANTE_IDENTIFICACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTE_GRUPO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."ESTUDIANTE_GRUPO" ADD CONSTRAINT "ESTUDIANTE_GRUPO_ESTUDIANTE_FK" FOREIGN KEY ("ESTUDIANTE_IDENTIFICACION")
	  REFERENCES "PRUEBA"."ESTUDIANTE" ("PERSONA_IDENTIFICACION") ENABLE;
  ALTER TABLE "PRUEBA"."ESTUDIANTE_GRUPO" ADD CONSTRAINT "ESTUDIANTE_GRUPO_GRUPO_FK" FOREIGN KEY ("GRUPO_ID")
	  REFERENCES "PRUEBA"."GRUPO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXAMEN
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."EXAMEN" ADD CONSTRAINT "EXAMEN_DOCENTE_FK" FOREIGN KEY ("DOCENTE_PERSONA_IDENTIFICACION")
	  REFERENCES "PRUEBA"."DOCENTE" ("PERSONA_IDENTIFICACION") ENABLE;
  ALTER TABLE "PRUEBA"."EXAMEN" ADD CONSTRAINT "EXAMEN_GRUPO_PK" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "PRUEBA"."GRUPO" ("ID") ENABLE;
  ALTER TABLE "PRUEBA"."EXAMEN" ADD CONSTRAINT "EXAMEN_TEMA_FK" FOREIGN KEY ("ID_TEMA")
	  REFERENCES "PRUEBA"."TEMA" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRUPO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."GRUPO" ADD CONSTRAINT "GRUPO_ASIGNATURA_FK" FOREIGN KEY ("ASIGNATURA_IDASIGNATURA")
	  REFERENCES "PRUEBA"."ASIGNATURA" ("IDASIGNATURA") ENABLE;
  ALTER TABLE "PRUEBA"."GRUPO" ADD CONSTRAINT "GRUPO_DOCENTE_FK" FOREIGN KEY ("DOCENTE_PERSONA_IDENTIFICACION")
	  REFERENCES "PRUEBA"."DOCENTE" ("PERSONA_IDENTIFICACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HORARIOO
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."HORARIOO" ADD CONSTRAINT "HORARIO_GRUPO_FK" FOREIGN KEY ("GRUPO_ID")
	  REFERENCES "PRUEBA"."GRUPO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OPCION
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."OPCION" ADD CONSTRAINT "OPCION_PREGUNTA_FK" FOREIGN KEY ("PREGUNTA_ID")
	  REFERENCES "PRUEBA"."PREGUNTA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."PERSONA" ADD CONSTRAINT "PERSONA_ROL_FK" FOREIGN KEY ("ROL_ID")
	  REFERENCES "PRUEBA"."ROL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."PREGUNTA" ADD CONSTRAINT "PREGUNTA_DOCENTE_FK" FOREIGN KEY ("DOCENTE_PERSONA_IDENTIFICACION")
	  REFERENCES "PRUEBA"."DOCENTE" ("PERSONA_IDENTIFICACION") ENABLE;
  ALTER TABLE "PRUEBA"."PREGUNTA" ADD CONSTRAINT "PREGUNTA_PREGUNTA_FK" FOREIGN KEY ("PREGUNTA_ID")
	  REFERENCES "PRUEBA"."PREGUNTA" ("ID") ENABLE;
  ALTER TABLE "PRUEBA"."PREGUNTA" ADD CONSTRAINT "PREGUNTA_PRIVACIDAD_FK" FOREIGN KEY ("PRIVACIDAD_ID")
	  REFERENCES "PRUEBA"."PRIVACIDAD" ("ID") ENABLE;
  ALTER TABLE "PRUEBA"."PREGUNTA" ADD CONSTRAINT "PREGUNTA_TEMA_FK" FOREIGN KEY ("TEMA_ID")
	  REFERENCES "PRUEBA"."TEMA" ("ID") ENABLE;
  ALTER TABLE "PRUEBA"."PREGUNTA" ADD CONSTRAINT "PREGUNTA_TIPO_PREGUNTA_FK" FOREIGN KEY ("TIPO_PREGUNTA_ID")
	  REFERENCES "PRUEBA"."TIPO_PREGUNTA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."RESPUESTA" ADD CONSTRAINT "RESPUESTA_PREGUNTA_FK" FOREIGN KEY ("PREGUNTA_ID")
	  REFERENCES "PRUEBA"."PREGUNTA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAS
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."RESPUESTAS" ADD CONSTRAINT "RESESTEXABAN_FK" FOREIGN KEY ("ESTEXBAN_EXAMENEST_ID", "ESTEXBAN_ESTEXA_ESTUDIANTE_ID", "ESTEXBAN_BANCO_EXAMEN_ID", "ESTEXBAN_BANCO_PREGUNTA_ID")
	  REFERENCES "PRUEBA"."ESTUDIANTE_EXAMEN_BANCO" ("EXAMENEST_ID", "ESTEXA_ESTUDIANTE_ID", "BANCO_EXAMEN_ID", "BANCO_PREGUNTA_ID") ENABLE;
  ALTER TABLE "PRUEBA"."RESPUESTAS" ADD CONSTRAINT "RESPUESTAS_OPCION_FK" FOREIGN KEY ("OPCION_ID")
	  REFERENCES "PRUEBA"."OPCION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEMA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."TEMA" ADD CONSTRAINT "TEMA_PLAN_ESTUDIO_FK" FOREIGN KEY ("PLAN_ESTUDIO_ID")
	  REFERENCES "PRUEBA"."PLAN_ESTUDIO" ("ID") ENABLE;
